name: deploy

on:
  push:
    branches: [ master ]
    paths:
      - 'server/**'

concurrency: server_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.SERVER_PRIVATE_KEY }}
          dep: deploy
          sub-directory: server
          deployer-version: "7.5.12"